language: node_js

node_js:
 - "0.10"

sudo: false

addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - g++-4.8

notifications:
  email:
    - jrgm@mozilla.com

before_install:
  - ls -la .
  - uname -a
  - cat /etc/lsb-release || echo 'no /etc/lsb-release'
  - gcc --version || echo 'no gcc?'
  - g++ --version || echo 'no g++?'
  - echo done

install:
  - gcc --version || echo 'no gcc?'
  - g++ --version || echo 'no g++?'
  - CXX=g++-4.8 gcc --version || echo 'no gcc?'
  - CXX=g++-4.8 g++ --version || echo 'no g++?'
  - npm install

