language: node_js

node_js:
 - "0.10"

sudo: false

notifications:
  email:
    - jrgm@mozilla.com

before_install:
  - ls -la .
  - uname -a
  - cat /etc/lsb-release || echo 'no /etc/lsb-release'
  - gcc --version
  - g++ --version
  - echo done

