language: node_js

node_js:
 - "0.10"

sudo: false

addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - g++-4.8

notifications:
  email:
    - jrgm@mozilla.com

before_install:
  - ls -la .
  - uname -a
  - cat /etc/lsb-release || echo 'no /etc/lsb-release'
  - gcc --version || echo 'no gcc?'
  - g++ --version || echo 'no g++?'
  - echo done

install:
  - env | sort
  - gcc --version || echo 'no gcc?'
  - g++ --version || echo 'no g++?'
  # use c++-11 with node4, default compiler on downlevel versions
  - if [ $TRAVIS_NODE_VERSION == "4" ]; then CXX=g++-4.8 npm install; else npm install; fi

