language: node_js

node_js:
 - "0.10"

notifications:
  email:
    - jrgm@mozilla.com

before_install:
  - sudo ls -l ./scripts

before_script:
 - "uname -a"
 - "[ -e /etc/lsb-release ] && cat /etc/lsb-release"
 - "phantomjs --version"
 - "mysql -NBe 'select version()'"
